tabela: main.o
	gcc main.o -o tabela
multiplication_table.o: multiplication_table.c
	gcc -c multiplication_table.c -o multiplication_table.o
multiplication_table_n.o: multiplication_table_n.c
	gcc -c multiplication_table_n.c -o multiplication_table_n.o
main.o: main.c
	gcc -c main.c -o main.o
